#!/usr/bin/env bash
# version: 1.1 | last_updated: 2026-04-04
# session-summary.sh — Stop hook
# Auto-generates a session summary to the vault on session end.
# Triggers QMD index refresh if available.
set -euo pipefail

DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

git rev-parse --git-dir >/dev/null 2>&1 || exit 0
REPO=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)")
CHANGED=$(git status --short 2>/dev/null)
RECENT_COMMITS=$(git log --oneline -3 2>/dev/null)

# QMD refresh (background, fire-and-forget) — runs BEFORE vault check
# so QMD stays fresh even if vault path is not configured
if command -v qmd >/dev/null 2>&1 && [[ -n "$CHANGED" || -n "$RECENT_COMMITS" ]]; then
  nohup bash -c 'qmd update >/dev/null 2>&1 && qmd embed >/dev/null 2>&1' >/dev/null 2>&1 &
  disown
fi

[[ -z "$CHANGED" && -z "$RECENT_COMMITS" ]] && exit 0

# Vault path resolution — AFTER QMD refresh (graceful exit if vault not found)
# Resolve config.sh relative to this script's location (works in both plugin and project mode)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_LIB="${CLAUDE_PLUGIN_ROOT:-$SCRIPT_DIR}/hooks/lib/config.sh"
[[ -f "$CONFIG_LIB" ]] || CONFIG_LIB="$SCRIPT_DIR/lib/config.sh"
[[ -f "$CONFIG_LIB" ]] || exit 0
source "$CONFIG_LIB"

SESSIONS_DIR="$VAULT/07-Claude/sessions"
mkdir -p "$SESSIONS_DIR"

# Deduplicate: skip if a recent session log already exists for today
for f in "$SESSIONS_DIR"/*"$DATE"*.md; do
  [[ -f "$f" ]] || continue
  age=$(( $(date +%s) - $(stat -f %m "$f" 2>/dev/null || echo 0) ))
  if [[ $age -lt 600 ]] && grep -qE "type: (log|session-log)" "$f" 2>/dev/null; then
    exit 0
  fi
done

SUMMARY_FILE="$SESSIONS_DIR/auto-$DATE-$TIMESTAMP.md"
{
  echo "---"
  echo "type: auto-summary"
  echo "date: $DATE"
  echo "project: $REPO"
  echo "topics: []"
  echo "---"
  echo ""
  echo "# Auto-summary — $REPO — $TIMESTAMP"
  echo ""
  echo "_Auto-generated by session-summary hook. Run /session-end for full WMS-synced close._"
  echo ""
  if [[ -n "$CHANGED" ]]; then
    echo "## Changed files"
    echo "$CHANGED"
    echo ""
  fi
  if [[ -n "$RECENT_COMMITS" ]]; then
    echo "## Recent commits"
    echo "$RECENT_COMMITS"
    echo ""
  fi
} > "$SUMMARY_FILE"

exit 0
